# fishrequired: amount of fish required to upgrade from level 3 to 4 (fish caught during level 1 and 2 count towards upgrade)
# placeholders: %player%
# rewards: command|percentage

broadcast-rankup: "&b&lA&d&lC&b Fishing: &d%player% &7has reached &dLevel %level%&7 on their Astro Rod!"
rewards-cmd-msg:
  - "Test"
level:
  1:
    fishrequired: 2
    commands:
      - ""
    rewards:
      - "give %player% iron_ingot 1|60"
      - "give %player% gold_ingot 1|50"
      - "give %player% coal 1|0.60"
      - "give %player% gold_ingot 1|40"
  2:
    fishrequired: 12
    commands:
      - "eco give %player% 500"
    rewards:
      - "give %player% iron_ingot 1|70"
      - "give %player% gold_ingot 1|50"
      - "give %player% iron_ingot 1|0.95"
      - "give %player% gold_ingot 1|0.25"
  3:
    fishrequired: 24
    commands:
      - "eco give %player% 650"
    rewards:
      - "give %player% fish 1|0.95"
      - "give %player% diamond 1|0.25"
  4:
    fishrequired: 36
    commands:
      - "eco give %player% 800"
    rewards:
      - "give %player% fish 1|0.95"
      - "give %player% diamond 1|0.25"
  5:
    fishrequired: 50
    commands:
      - "eco give %player% 1500"
    rewards:
      - "give %player% fish 1|0.95"
      - "give %player% diamond 1|0.25"
  6:
    fishrequired: 120
    commands:
      - "eco give %player% 2500"
    rewards:
      - "give %player% fish 1|0.95"
      - "give %player% diamond 1|0.25"
  7:
    fishrequired: 180
    commands:
      - "eco give %player% 5000"
    rewards:
      - "give %player% fish 1|0.95"
      - "give %player% diamond 1|0.25"
  8:
    fishrequired: 300
    commands:
      - "eco give %player% 8000"
    rewards:
      - "give %player% fish 1|0.95"
      - "give %player% diamond 3|0.25"
  9:
    fishrequired: 700
    commands:
      - "eco give %player% 10000"
    rewards:
      - "ss give %player% cow 1|9"
      - "ss give %player% witch 1|3"
      - "ss give %player% enderman 1|1"
      - "ss give %player% creeper 1|2"
      - "ss give %player% pig 1|11"
      - "ss give %player% chicken 1|12"
  10:
    fishrequired: 1000
    commands:
      - "eco give %player% 50000"
    rewards:
      - "cr give %player% Typical 1|1"
      - "cr give %player% Epic 1|0.75"
      - "cr give %player% Demise 1|0.50"
      - "ss give %player% creeper 1|3"
      - "ss give %player% witch 1|4"
      - "ss give %player% enderman 1|2"
      - "kit warrior %player% |20"
      - "kit duke %player% |12"
      - "kit titan %player% |10"
      - "eco give %player% 1500|0.75"
      - "eco give %player% 5000|0.50"